title: Rambling Thoughts of Steeladept
author: Thomas Higgins

description: > # this means to ignore newlines until "baseurl:"
  The notes, scribbles, and occasionally inspired
  musings of an IT Generalist and DevOps Engineer.

# social links
twitter_username: DevOpsThomas
github_username:  steeladept

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot